export enum HttpStatus {
    SUCCESS = "SUCCESS",
    SERVER_ERROR = "SERVER_ERROR",
    USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
    ERROR = "ERROR",
    USER_NOT_FOUND = "USER_NOT_FOUND",
    UNAUTHORIZED = "UNAUTHORIZED"
}
